source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'ClusterKit', :path => '../.'
pod 'ClusterKit/Mapbox', :path => '../.'

target 'Example-data' do
    pod 'GeoJSONSerialization'
end

target 'Example-objc' do
    pod 'GoogleMaps'
    pod 'YandexMapKit'
end

target 'Example-swift' do
    pod 'GoogleMaps'
    pod 'YandexMapKit'
end

